### ISSUE TITLE
The plugin tries to lint .d.ts files and throws error

### ISSUE THREAD

**Issue by alisnic** [quavedev/eslint-plugin#11]
```
SyntaxError: Unexpected token ','. (60:1)
Occurred while linting /Users/andreilisnic/Work/planable-app/@types/array.d.ts:1
Rule: "@quave/meteor-quave/no-sync-mongo-methods-on-server"
    at constructor (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:356:19)
    at FlowParserMixin.raise (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:3223:19)
    at FlowParserMixin.parseExprListItem (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:12000:14)
    at FlowParserMixin.parseCallExpressionArguments (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:11054:22)
    at FlowParserMixin.parseCoverCallAndAsyncArrowHead (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10964:29)
    at FlowParserMixin.parseSubscript (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10899:19)
    at FlowParserMixin.parseSubscript (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:5858:18)
    at FlowParserMixin.parseSubscripts (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10870:19)
    at FlowParserMixin.parseSubscripts (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:5824:18)
    at FlowParserMixin.parseExprSubscripts (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10861:17)

```

**Comment by alisnic** [comment]
As a workaround, ignorePatterns can be added to eslint config
