### ISSUE TITLE
SyntaxError: Unexpected token ','

### ISSUE THREAD

**Issue by alisnic** [quavedev/eslint-plugin#12]
The contents of the file do not matter, if I remove it it fails on the next file. If I disable the plugin, there are no errors.

```
  eslint:file-enumerator Yield: activity.tests.ts +0ms
  eslintrc:cascading-config-array-factory Load config files for /Users/andreilisnic/Work/planable-app/imports/api/activity. +0ms
  eslintrc:cascading-config-array-factory Cache hit: /Users/andreilisnic/Work/planable-app/imports/api/activity. +0ms
  eslint:cli-engine Lint /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +0ms
  eslint:linter Linting code for /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts (pass 1) +0ms
  eslint:linter Verify +0ms
  eslint:linter With ConfigArray: /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +0ms
  eslint:config-comment-parser Parsing list config +0ms
  eslint:linter Parsing: /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +2ms
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.4.2

Please only submit bug reports when using the officially supported version.

=============
  eslint:linter Parsing successful: /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +10s
  eslint:linter Scope analysis: /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +0ms
  eslint:linter Scope analysis successful: /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +0ms
Cache is not going to be used
Starting from meteor.mainModule.server from package.json server/main.ts
Processing file no-sync-mongo-methods-on-server /Users/redacted1.ts
...SNIP...
Processing file no-sync-mongo-methods-on-server /Users/redactedN.ts
  eslint:linter An error occurred while traversing +3s
  eslint:linter Filename: /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts +0ms
  eslint:linter Line: 3 +0ms
  eslint:linter Parser Options: {
  ecmaFeatures: {
    globalReturn: false,
    jsx: true,
    experimentalObjectRestSpread: true
  },
  ecmaVersion: 11,
  parser: '@typescript-eslint/parser',
  tsconfigRootDir: '/Users/andreilisnic/Work/planable-app',
  project: [ './tsconfig.json' ],
  allowImportExportEverywhere: true,
  sourceType: 'module'
} +0ms
  eslint:linter Parser Path: /Users/andreilisnic/Work/planable-app/node_modules/@typescript-eslint/parser/dist/index.js +0ms
  eslint:linter Settings: {} +0ms

Oops! Something went wrong! :(

ESLint: 8.57.0

SyntaxError: Unexpected token ','. (60:1)
Occurred while linting /Users/andreilisnic/Work/planable-app/imports/api/activity/activity.tests.ts:3
Rule: "@quave/meteor-quave/no-sync-mongo-methods-on-server"
    at constructor (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:356:19)
    at FlowParserMixin.raise (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:3223:19)
    at FlowParserMixin.parseExprListItem (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:12000:14)
    at FlowParserMixin.parseCallExpressionArguments (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:11054:22)
    at FlowParserMixin.parseCoverCallAndAsyncArrowHead (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10964:29)
    at FlowParserMixin.parseSubscript (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10899:19)
    at FlowParserMixin.parseSubscript (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:5858:18)
    at FlowParserMixin.parseSubscripts (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10870:19)
    at FlowParserMixin.parseSubscripts (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:5824:18)
    at FlowParserMixin.parseExprSubscripts (/Users/andreilisnic/Work/planable-app/node_modules/@babel/parser/lib/index.js:10861:17)
Rule                                                | Time (ms) | Relative
:---------------------------------------------------|----------:|--------:
@quave/meteor-quave/no-sync-mongo-methods-on-server |     0.067 |    49.4%
@quave/meteor-quave/no-sync-user-methods-on-server  |     0.027 |    20.3%
@quave/meteor-quave/no-fibers-future-usage          |     0.020 |    14.9%
@quave/meteor-quave/no-promise-fibers-usage         |     0.013 |     9.4%
@quave/meteor-quave/no-meteor-wrap-async-usage      |     0.008 |     6.0%
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

**Comment by alisnic** [comment]
Update, it seems the problem lies in the following rules:
- no-sync-mongo-methods-on-server
- no-sync-user-methods-on-server

If I disable them, everything works fine
